In [ ]:
def game():
    ans=(input('Would you like to play tic tac toe game?'))
    if ans == 'yes':
        player1 = input('Please pick a marker X or O')

In [8]:
n = int(input()) 
a = []
for i in range(n):
    row = input().split()
    for i in range(len(row)):
        row[i] = int(row[i])
    a.append(row)

3
12
7
9


In [10]:
n = int(input()) 
a = [[int(j) for j in input().split()] for i in range(n)]

2
2
4


In [11]:
a

[[2], [4]]

In [12]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
